hashtag_list = [
# This is a sample hashtag list. Please enter your hashtag list (without the comment).
#            "london",
#            "paris",
#            "newyork",
#            "tokyo"
            "uyghur",
            "uyghur2021",
            "uyghur2022",
            "uyghurmuslims",
            "xinjiang",
            "xinjiangchina",
            "xinjiangcotton",
            "xinjiangtravel",
            "uyghurlivesmatter",
            "uighur",
            "Uighurs",
            "Uyghurs",
            "uighuren",
            "saveuyghur",
            "uighurmuslims",
            "chinesemuslim",
            "uyghurpeople",
            "urumqi",
            "chinaxinjiang",
            "xinjianguyghurs",
            "eastturkestan",
            "chinaconcentrationcamp",
            "xinjianguyghur🇨🇳",
            "kashgar",
            "xinjiangreeducationcamps",
            "uyghur_tiktok",
            "uyghurreality",
            "xinjiangdance",
            "westernmedia",
            "uyghurgenocide"
        ]
